
import java.lang.Math; 
import java.util.*;


// The game is to guess the random number generated by the computer.
// In each round the user guesses one. User can keep playing more 
// and more rounds as long as they wish.

public class GuessingGamePlayer
{

    public static void main(String[] args)
    {
        GuessingGame myGame = new GuessingGame(15);
        myGame.play();
    }
}

class GuessingGame
{
    private static Scanner mInput = new Scanner(System.in);
    private int mLimit;

    public GuessingGame(int _limit) 
    {
        mLimit = _limit;
    }

    public void play()
    {
        boolean continuePlaying = true;
        while(continuePlaying)
        {
            playOneRound();
            continuePlaying = askContinue();
        }
    }

    private boolean askContinue()
    {
        System.out.print("Play another round? : ");
        String respose = mInput.next(); // next token
        if (respose.equalsIgnoreCase("y") || respose.equalsIgnoreCase("yes")) {
            return true;
        }
        else return false;
    } 

    private void playOneRound()
    {
        System.out.println("Hi Let's play the guessing game baby.");

        // random number generation

        int reference = (int) (Math.random() * mLimit) + 1;
        System.out.println("reference : " + reference);

        // retrieve users guess
        System.out.print("Enter your guess (between 1 to " + mLimit +") : ");
        int guess = mInput.nextInt();


        // compare guess to reference
        if (guess == reference) {
            System.out.println("Good guess, buddy!");
        }
        else {
            System.out.println("Ah, bad luck mate.");
        }
    } // playOneRound()
} // class GuessingGame



